# 9. 예외 처리

- 복구가 가능한 것을 말한다
- 특히 try , exepct를 손에 익히는 것이 중요함

------

- 예외 발생을 감지하고 복구하는 방법

```python
try:
	실행할 명령
except 예외 as 변수:
	오류 처리문
else:	                     #else는 선택사항
	예외가 발생하지 않았을때 의 처리
```

예제들

```python
str ='89점'
try:
    score = int(str)  ## 여기서 int가 안되면(다른 type의 데이터가 포함되면) except로 들어가게된다.
    print(score)
except:
    print("예외가 발생했습니다.")

print('작업완료')
```

```python
while True:
    str = input('점수를 입력하세요 :')
    try:
        score = int(str)			#여기서 막히면?
        print('입력점수 :', score)
        break                       # break문을 통해 except 로 가게된다.
    except:
        print('점수 형식이 잘못되었습니다.')

print('작업완료')
```

----



- 예외의 종류

| 이름               | 뜻                                            |
| ------------------ | --------------------------------------------- |
| NameError          | Not defined 으로 a = ㅁ  뭐인지 선언 안해준거 |
| ValueError         | int, str 처럼 충돌되는게 있을때               |
| Zero DivisionError | /0 으로 나누었을때 발생하는 오류              |
| IndexError         | index 범위에 없을때                           |
| TypeError          | List, dic 등 서로 연산등 상호작용이 안될때    |

-예제

```python
str = input("성적을 입력하세요 :")
try:
    score =int(str)
    print(score)
    a=str[0]
    
# 1번방식    
except ValueError:
    print('점수 형식이 잘못되었습니다')
except IndexError:
    print('첨자 범위를 벗어났습니다')

# 2번방식
except (ValueError, IndexError):
    print("점수의 형식이나 첨자가 잘못되었습니다")

print('작업완료')
```



- raise
  - 개발자에 의해 임의로 예외를 발생시킴

```python
def calcsum(n):
    if n<0 :
        raise ValueError     # 개발자가 임의로 에러를 낸다
                            # raise ValueError자리에 return None 해버려도 같은 의미임
    total =0 
    for i in range(n+1):
        total +=i
    return total

try:
    print("~10=", calcsum(10))
    print("~-5=" ,calcsum(-5))   #예외처리는 실패하는 경우는 신경쓸 필요 없다.실패하면 예외블럭으로 가니깐
except ValueError:
    print("입력값이 잘못되었습니다")
```



- **finally**  **--- 중요~~!!!!!!!!!!**
  - 예외 발생 여부와 상관없이 항상 호출
  - 작업의 마무리 작업(cleanup) 수행 
  - ex) 중간에 뭐든간에 마지막 통신 망에 나오는걸 봐야할때 

```python
# 간단한 문구
try:
    print("네트워크 접속")
    a = 2/0
    print('네트워크 통신 수행')    # 통신을 수행하든 말든 접속해제는 해야된다

finally:                        # 그래서 finally를 꼭 써준다
    print('접속 해제')

print('작업 완료')
```

```python
# 복잡한 문구
def chat():
    try:
        print('네트워크 접속')
        return#a=2                       # return이 있으면 이면 try 블럭이 끝난다
        print('네트워크 통신 수행')
    except:
        print('네트워크 에러 발생')
    finally:                         # 함수 실행 끝날때 반드시 여기에 들린다.
        print('접속 해제')
        print("==================")

print('통신을 시작합니다')
chat()
print('통신이 끝났습니다')
```



- assert         단정, 확정문
  - assert 조건, 메시지
    - 조건이 True이면 통과,
    - False이면 메시지를 가지는 예외 발생

```python
score = 128
assert score <= 100, "점수는 100 이하여야 합니다."
print(score)
# score가 100 이하라면 그냥 뽑아내고
# 이 경우 에러가 발생하며 그떄 100 이하 문구를 출력한다.

```

